import os
import datetime

def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to Markdown file with proper formatting"""
    if not response_text:
        print("Warning: No response text provided.")
        return None

    try:
        os.makedirs(directory, exist_ok=True)

        # Create markdown content
        markdown_content = f"""# 🌍 AI Travel Plan

# **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
# **Created by:** Abhishek's Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""

        # Create full directory path
        full_directory = os.path.join(directory, "AI_TRAVEL_AGENT", "SAVED_DOCS")
        os.makedirs(full_directory, exist_ok=True)

        # Generate filename
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = os.path.join(full_directory, f"{timestamp}.md")

        # Write to file
        print("Writing to file:", filename)
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)

        print(f"✅ Markdown file saved as: {filename}")
        return filename

    except Exception as e:
        print(f"❌ Error saving markdown file: {e}")
        return None
