llm:
  openai:
    provider: "openai"
    model_name: "o4-mini"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  openrouter:
    provider: "openrouter"  
    model_name: "mistralai/mistral-small-3.2-24b-instruct"